CREATE DATABASE COMPANYDB;

USE COMPANYDB;

CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY,
USER_NAME VARCHAR(50) NOT NULL,
AGE INT,
COUNTRY VARCHAR(50),
AMOUNT_SPEND INT
);

INSERT INTO CUSTOMERS (ID,USER_NAME,AGE,COUNTRY,AMOUNT_SPEND)
VALUES
(1, 'Rahul', 25, 'India', 15000),
(2, 'Priya', 28, 'India', 22000),
(3, 'Amit', 32, 'India', 18000),
(4, 'Neha', 24, 'India', 12000),
(5, 'John', 35, 'USA', 30000),
(6, 'Sarah', 29, 'UK', 25000),
(7, 'David', 41, 'Canada', 35000),
(8, 'Emma', 27, 'Australia', 20000),
(9, 'Rohan', 30, 'India', 28000),
(10, 'Sophia', 33, 'USA', 32000); 

SELECT * FROM CUSTOMERS;

SELECT USER_NAME,AGE FROM CUSTOMERS;

SELECT * FROM CUSTOMERS
WHERE AGE>30;

SELECT * FROM CUSTOMERS
WHERE AGE >30 AND COUNTRY='INDIA';

SELECT * FROM CUSTOMERS
WHERE COUNTRY='INDIA' AND USER_NAME LIKE '%A';

-- %A = End A
-- A% = start A
-- %A% = Contains A

SELECT * FROM CUSTOMERS
WHERE AMOUNT_SPEND BETWEEN 20000 AND 30000;

SELECT * FROM CUSTOMERS
ORDER BY AGE ASC;

SELECT * FROM CUSTOMERS
WHERE AGE > 30
ORDER BY AMOUNT_SPEND DESC;

SELECT TOP 2* FROM CUSTOMERS
WHERE AGE > 30
ORDER BY AMOUNT_SPEND DESC;